# -*- coding: utf-8 -*-
"""exp-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJRpJp3k4fA3AV-zF2njx2mCXDgKsK4I
"""

!pip install -q -U google-genai

import getpass
from google import genai

# =========================================================
# EXPERIMENT 10
# SQL QUERY GENERATION USING STRUCTURED PROMPTING
# =========================================================

print("=" * 60)
print("SQL QUERY GENERATION USING STRUCTURED PROMPTING")
print("=" * 60)

# Enter Gemini API key
api_key = getpass.getpass("Enter your Gemini API key: ")

client = genai.Client(api_key=api_key)

print("\nGemini API connected successfully!")


# =========================================================
# DATABASE SCHEMA
# =========================================================

schema = """
DATABASE: CollegeDB

TABLE: Students
Columns:
student_id INT
name VARCHAR
department VARCHAR
year INT
cgpa FLOAT

TABLE: Courses
Columns:
course_id INT
course_name VARCHAR
credits INT

TABLE: Enrollments
Columns:
student_id INT
course_id INT
semester VARCHAR
"""


# =========================================================
# USER REQUIREMENT
# =========================================================

requirement = input(
    "\nEnter the SQL query requirement:\n"
)


# =========================================================
# STRUCTURED PROMPT
# =========================================================

structured_prompt = f"""
ROLE:
You are an expert SQL developer.

DATABASE SCHEMA:
{schema}

USER REQUIREMENT:
{requirement}

INSTRUCTIONS:
1. Generate a correct SQL query.
2. Use only the tables and columns given in the schema.
3. Use standard SQL syntax.
4. Use appropriate SELECT, WHERE, JOIN, GROUP BY,
   ORDER BY or other clauses when required.
5. Do not invent table names or column names.
6. Return only the SQL query.
"""


# =========================================================
# GENERATE SQL
# =========================================================

try:

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=structured_prompt
    )

    generated_sql = response.text.strip()

    # Remove Markdown code fences if present
    generated_sql = generated_sql.replace("```sql", "")
    generated_sql = generated_sql.replace("```", "")
    generated_sql = generated_sql.strip()

    print("\n" + "=" * 60)
    print("GENERATED SQL QUERY")
    print("=" * 60)

    print(generated_sql)


    # =====================================================
    # BASIC VALIDATION
    # =====================================================

    print("\n" + "=" * 60)
    print("SQL VALIDATION")
    print("=" * 60)

    sql_upper = generated_sql.upper()

    if sql_upper.startswith("SELECT"):
        print("✓ SQL starts with SELECT.")
    else:
        print("✗ Generated output does not start with SELECT.")

    # Check for table names
    tables_found = []

    for table in ["STUDENTS", "COURSES", "ENROLLMENTS"]:
        if table in sql_upper:
            tables_found.append(table)

    if tables_found:
        print("✓ Tables used:", ", ".join(tables_found))
    else:
        print("⚠ No known table name detected.")

    # Basic semicolon check
    if generated_sql.endswith(";"):
        print("✓ Query ends with semicolon.")
    else:
        print("⚠ Semicolon is missing.")

    print("\nSQL query generation and validation completed.")


except Exception as e:

    print("\nError occurred:")
    print(e)