# -*- coding: utf-8 -*-
"""exp-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16efK8vWNg73fc74Oxn7bYO6Rsjt8FBaa
"""

!pip install -q -U google-genai

from huggingface_hub import InferenceClient
import getpass

# =========================================================
# EXPERIMENT 8
# TEXT GENERATION USING HUGGING FACE INFERENCE API
# =========================================================

print("=" * 60)
print("HUGGING FACE TEXT GENERATION APPLICATION")
print("=" * 60)

# Enter Hugging Face token securely
token = getpass.getpass("Enter your Hugging Face API token: ")

# Create Inference Client
client = InferenceClient(
    api_key=token
)

# Get prompt from user
prompt = input("\nEnter your prompt: ")

try:

    # Generate text using Hugging Face Inference API
    response = client.text_generation(
        prompt,
        model="HuggingFaceH4/zephyr-7b-beta",
        max_new_tokens=150
    )

    print("\n" + "=" * 60)
    print("GENERATED OUTPUT")
    print("=" * 60)

    print(response)

except Exception as e:

    print("\nError occurred:")
    print(e)