# -*- coding: utf-8 -*-
"""exp-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16efK8vWNg73fc74Oxn7bYO6Rsjt8FBaa
"""

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="distilgpt2"
)

# Zero-shot prompt
zero_shot = """
Write a product description for a Smart Fitness Watch.
"""

# One-shot prompt
one_shot = """
Example:
Product: Wireless Earbuds
Description: Premium wireless earbuds with clear sound,
long battery life and a comfortable design.

Now generate a product description for:
Product: Smart Fitness Watch
"""

# Few-shot prompt
few_shot = """
Example 1:
Product: Smart Phone
Description: A powerful smartphone with a high-resolution
display, advanced camera and long-lasting battery.

Example 2:
Product: Fitness Band
Description: A lightweight fitness band that tracks steps,
heart rate, calories and daily activity.

Now generate a product description for:
Product: Smart Fitness Watch
"""

def generate(prompt):
    result = generator(
        prompt,
        max_new_tokens=100,
        num_return_sequences=1,
        do_sample=True
    )
    return result[0]["generated_text"]

print("===== ZERO-SHOT =====")
print(generate(zero_shot))

print("\n===== ONE-SHOT =====")
print(generate(one_shot))

print("\n===== FEW-SHOT =====")
print(generate(few_shot))
