# -*- coding: utf-8 -*-
"""exp-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16efK8vWNg73fc74Oxn7bYO6Rsjt8FBaa
"""

!pip install -q transformers sentencepiece

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# =========================================================
# Q4: PROFESSIONAL LEAVE EMAIL
# Zero-shot, One-shot and Few-shot Prompting
# =========================================================

MODEL_NAME = "google/flan-t5-small"

print("Loading model...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

print("Model loaded successfully!")
print("Device:", device)


# =========================================================
# TEXT GENERATION FUNCTION
# =========================================================

def generate_text(prompt, max_tokens=180):

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        max_length=512,
        truncation=True
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.no_grad():

        outputs = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            num_beams=4,
            do_sample=False
        )

    return tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )


# =========================================================
# ZERO-SHOT PROMPT
# =========================================================

zero_shot_prompt = """
Write a professional email requesting leave from college
due to illness.

The email should include:
- Subject
- Greeting
- Reason for leave
- Request for leave
- Polite closing
"""


# =========================================================
# ONE-SHOT PROMPT
# =========================================================

one_shot_prompt = """
Example:

Task: Write a professional leave email due to a family emergency.

Answer:

Subject: Leave Request Due to Family Emergency

Dear Professor,

I am writing to request leave from college due to an urgent
family emergency. I kindly request you to grant me leave for
one day. I will complete the missed academic work after
returning to college.

Thank you for your understanding.

Regards,
Student

Now write a professional email requesting leave due to illness.
Include subject, greeting, reason, leave request and polite closing.
"""


# =========================================================
# FEW-SHOT PROMPT
# =========================================================

few_shot_prompt = """
Example 1:

Task: Request leave for a medical appointment.

Answer:

Subject: Leave Request for Medical Appointment

Dear Professor,

I kindly request leave for one day as I have a medical
appointment. I will complete all the academic work that
I miss during my absence.

Regards,
Student


Example 2:

Task: Request leave due to a family emergency.

Answer:

Subject: Leave Request Due to Family Emergency

Dear Professor,

I am writing to request leave due to an unexpected family
emergency. I kindly request you to grant me leave for one day.
I will complete any missed academic work.

Thank you.

Regards,
Student


Now write a professional email requesting leave due to illness.

Requirements:
- Professional tone
- Correct grammar
- Subject line
- Greeting
- Explain illness
- Request leave
- Mention missed work
- Polite closing
"""


# =========================================================
# GENERATE OUTPUTS
# =========================================================

print("\n" + "=" * 70)
print("ZERO-SHOT EMAIL")
print("=" * 70)

zero_result = generate_text(
    zero_shot_prompt
)

print(zero_result)


print("\n" + "=" * 70)
print("ONE-SHOT EMAIL")
print("=" * 70)

one_result = generate_text(
    one_shot_prompt
)

print(one_result)


print("\n" + "=" * 70)
print("FEW-SHOT EMAIL")
print("=" * 70)

few_result = generate_text(
    few_shot_prompt
)

print(few_result)


# =========================================================
# COMPARISON
# =========================================================

print("\n" + "=" * 70)
print("COMPARISON")
print("=" * 70)

print("""
Evaluate the three generated emails using:

1. TONE
   Is the email professional and polite?

2. GRAMMAR
   Is the language grammatically correct?

3. FORMATTING
   Does it contain subject, greeting, body and closing?

4. COMPLETENESS
   Does it clearly mention illness, leave request and
   responsibility for missed work?

Generally, the Few-shot prompt should provide better
format and completeness because examples are provided.
""")