# -*- coding: utf-8 -*-
"""exp-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16efK8vWNg73fc74Oxn7bYO6Rsjt8FBaa
"""

!pip install -q transformers sentencepiece

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# ---------------------------------------------------------
# Q3: ZERO-SHOT, ONE-SHOT AND FEW-SHOT SUMMARIZATION
# ---------------------------------------------------------

MODEL_NAME = "google/flan-t5-small"

print("Loading model...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

print("Model loaded successfully!")
print("Device:", device)


# ---------------------------------------------------------
# GENERATION FUNCTION
# ---------------------------------------------------------

def generate_text(prompt, max_length=100):

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        max_length=512,
        truncation=True
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.no_grad():

        output = model.generate(
            **inputs,
            max_new_tokens=max_length,
            num_beams=4,
            do_sample=False
        )

    return tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )


# ---------------------------------------------------------
# ARTICLE
# ---------------------------------------------------------

article = """
Artificial intelligence is transforming modern industries by enabling
machines to analyze large amounts of data, identify patterns and support
decision making. In healthcare, artificial intelligence is used for medical
image analysis, disease prediction, drug discovery and personalized treatment.
In transportation, intelligent systems support route optimization and
autonomous driving. Manufacturing industries use intelligent systems for
predictive maintenance, quality inspection and process automation.

These technologies can improve efficiency, reduce operational costs and
help organizations make faster decisions. However, the adoption of artificial
intelligence also creates challenges related to privacy, security, fairness,
employment and ethical decision making. Organizations therefore need
responsible practices when developing and deploying intelligent systems.
"""


# ---------------------------------------------------------
# ZERO-SHOT PROMPT
# ---------------------------------------------------------

zero_shot_prompt = f"""
Summarize the following article in approximately 50 words.

Article:
{article}
"""


# ---------------------------------------------------------
# ONE-SHOT PROMPT
# ---------------------------------------------------------

one_shot_prompt = f"""
Example:

Article:
Solar energy is a renewable source of energy that uses sunlight to produce
electricity. It reduces dependence on fossil fuels and helps decrease
environmental pollution.

Summary:
Solar energy produces clean electricity from sunlight, reducing fossil fuel
dependence and environmental pollution.

Now summarize the following article in approximately 50 words.

Article:
{article}
"""


# ---------------------------------------------------------
# FEW-SHOT PROMPT
# ---------------------------------------------------------

few_shot_prompt = f"""
Example 1:

Article:
Electric vehicles use electric motors instead of conventional engines.
They can reduce fuel consumption and emissions and are becoming increasingly
popular.

Summary:
Electric vehicles use electric motors and can reduce fuel consumption and
environmental emissions.

Example 2:

Article:
Cloud computing provides computing resources through the internet.
Organizations can access storage and processing power without maintaining
large physical infrastructure.

Summary:
Cloud computing provides internet-based computing resources and reduces the
need for physical infrastructure.

Now summarize the following article in approximately 50 words.

Article:
{article}
"""


# ---------------------------------------------------------
# GENERATE RESULTS
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("ZERO-SHOT SUMMARY")
print("=" * 70)

zero_result = generate_text(
    zero_shot_prompt,
    max_length=80
)

print(zero_result)


print("\n" + "=" * 70)
print("ONE-SHOT SUMMARY")
print("=" * 70)

one_result = generate_text(
    one_shot_prompt,
    max_length=80
)

print(one_result)


print("\n" + "=" * 70)
print("FEW-SHOT SUMMARY")
print("=" * 70)

few_result = generate_text(
    few_shot_prompt,
    max_length=80
)

print(few_result)


# ---------------------------------------------------------
# COMPARISON
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("COMPARISON CRITERIA")
print("=" * 70)

print("""
1. ACCURACY
   Does the summary correctly represent the article?

2. COMPLETENESS
   Does it contain the major ideas from the article?

3. READABILITY
   Is the summary clear, concise and easy to understand?

4. FORMAT
   Does the summary approximately follow the 50-word requirement?
""")