# -*- coding: utf-8 -*-
"""exp-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16efK8vWNg73fc74Oxn7bYO6Rsjt8FBaa
"""

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="distilgpt2"
)

zero_shot = """
Write a 200-word blog on "Applications of Artificial Intelligence in Healthcare."
"""

one_shot = """
Example blog:

Title: Technology in Education

Technology has transformed education by providing students
with online resources, digital classrooms and interactive
learning platforms.

Now write a 200-word blog on:
Applications of Artificial Intelligence in Healthcare.
"""

few_shot = """
Example 1:
Topic: Technology in Education
Write a short informative blog explaining how technology
improves learning and accessibility.

Example 2:
Topic: Digital Healthcare
Write a short informative blog explaining how digital
technology improves healthcare services.

Now write a 200-word blog on:
Applications of Artificial Intelligence in Healthcare.
"""

def generate(prompt):
    result = generator(
        prompt,
        max_new_tokens=250,
        do_sample=True
    )
    return result[0]["generated_text"]

print("===== ZERO-SHOT =====")
print(generate(zero_shot))

print("\n===== ONE-SHOT =====")
print(generate(one_shot))

print("\n===== FEW-SHOT =====")
print(generate(few_shot))