# -*- coding: utf-8 -*-
"""exp-9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJRpJp3k4fA3AV-zF2njx2mCXDgKsK4I
"""

!pip install -q -U google-genai

import getpass
from google import genai

# =========================================================
# EXPERIMENT 9
# PYTHON CODE GENERATION USING STRUCTURED PROMPTING
# =========================================================

print("=" * 60)
print("PYTHON CODE GENERATION USING STRUCTURED PROMPTING")
print("=" * 60)

# Gemini API key
api_key = getpass.getpass("Enter your Gemini API key: ")

client = genai.Client(api_key=api_key)

print("\nGemini API connected successfully!")


# =========================================================
# USER PROBLEM
# =========================================================

problem = input(
    "\nEnter the computational problem for which Python code "
    "should be generated:\n"
)


# =========================================================
# STRUCTURED PROMPT
# =========================================================

structured_prompt = f"""
ROLE:
You are an expert Python programmer.

TASK:
Generate a Python program for the following computational problem:

{problem}

REQUIREMENTS:
1. Use Python.
2. Use clear variable names.
3. Use a function wherever appropriate.
4. Accept input from the user.
5. Display the result clearly.
6. Handle basic invalid input where appropriate.
7. Include comments explaining important steps.
8. Return only the Python program.
"""


# =========================================================
# GENERATE CODE
# =========================================================

try:

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=structured_prompt
    )

    generated_code = response.text

    print("\n" + "=" * 60)
    print("GENERATED PYTHON CODE")
    print("=" * 60)

    print(generated_code)


    # =====================================================
    # VALIDATE GENERATED CODE
    # =====================================================

    print("\n" + "=" * 60)
    print("CODE VALIDATION")
    print("=" * 60)

    # Remove Markdown code fences if present
    clean_code = generated_code.replace("```python", "")
    clean_code = clean_code.replace("```", "")
    clean_code = clean_code.strip()

    try:

        compile(clean_code, "<generated_code>", "exec")

        print("✓ Syntax validation successful.")
        print("✓ Generated code is syntactically valid Python.")

    except SyntaxError as error:

        print("✗ Syntax error found.")
        print("Line:", error.lineno)
        print("Error:", error.msg)


except Exception as e:

    print("\nError occurred:")
    print(e)