# -*- coding: utf-8 -*-
"""exp-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16efK8vWNg73fc74Oxn7bYO6Rsjt8FBaa
"""

!pip install -q -U google-genai

import getpass
from google import genai

# =========================================================
# EXPERIMENT 7
# TEXT GENERATION USING GOOGLE GEMINI LLM API
# =========================================================

print("=" * 60)
print("GOOGLE GEMINI TEXT GENERATION APPLICATION")
print("=" * 60)

# Enter API key securely
api_key = getpass.getpass("Enter your Gemini API key: ")

# Create Gemini client
client = genai.Client(api_key=api_key)

print("\nGemini API connected successfully!")

# Get user prompt
prompt = input("\nEnter your prompt: ")

try:

    # Use the current Interactions API
    interaction = client.interactions.create(
        model="gemini-3.5-flash-lite",
        input=prompt
    )

    print("\n" + "=" * 60)
    print("GENERATED OUTPUT")
    print("=" * 60)

    print(interaction.output_text)

except Exception as e:

    print("\nError occurred:")
    print(e)