# -*- coding: utf-8 -*-
"""exp-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16efK8vWNg73fc74Oxn7bYO6Rsjt8FBaa
"""

!pip install -q transformers sentencepiece

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# =========================================================
# Q5: PROMOTIONAL SOCIAL MEDIA POST FOR AN AI WORKSHOP
# Zero-shot, One-shot and Few-shot Prompting
# =========================================================

MODEL_NAME = "google/flan-t5-small"

print("Loading model...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model = model.to(device)

print("Model loaded successfully!")
print("Device:", device)


# =========================================================
# TEXT GENERATION FUNCTION
# =========================================================

def generate_text(prompt, max_tokens=150):

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        max_length=512,
        truncation=True
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.no_grad():

        outputs = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            num_beams=4,
            do_sample=False
        )

    return tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )


# =========================================================
# ZERO-SHOT PROMPT
# =========================================================

zero_shot_prompt = """
Create a promotional social media post for an AI Workshop.

Include:
- Attractive heading
- Workshop benefits
- Call to action
- Hashtags
"""


# =========================================================
# ONE-SHOT PROMPT
# =========================================================

one_shot_prompt = """
Example:

Workshop: Python Programming Workshop

Social Media Post:
Join our exciting Python Programming Workshop!
Learn Python fundamentals through practical examples
and hands-on activities. Build your programming skills
and start creating useful applications.

Register now and begin your coding journey!

#Python #Programming #Workshop #Students

Now create a promotional social media post for an AI Workshop.

Include:
- Attractive heading
- Benefits
- Call to action
- Hashtags
"""


# =========================================================
# FEW-SHOT PROMPT
# =========================================================

few_shot_prompt = """
Example 1:

Workshop: Web Development Workshop

Post:
Build your web development skills!
Learn how to create modern websites using practical
examples and hands-on activities.

Register today and start building amazing websites!

#WebDevelopment #Workshop #Students


Example 2:

Workshop: Data Science Workshop

Post:
Discover the world of Data Science!
Learn data analysis, visualization and practical
techniques through an interactive workshop.

Don't miss this opportunity. Register now!

#DataScience #Workshop #Learning


Now create a promotional social media post for an AI Workshop.

Requirements:
- Create an attractive heading
- Explain workshop benefits
- Make it suitable for college students
- Include a strong call to action
- Include relevant hashtags
"""


# =========================================================
# GENERATE RESULTS
# =========================================================

print("\n" + "=" * 70)
print("ZERO-SHOT OUTPUT")
print("=" * 70)

zero_result = generate_text(zero_shot_prompt)
print(zero_result)


print("\n" + "=" * 70)
print("ONE-SHOT OUTPUT")
print("=" * 70)

one_result = generate_text(one_shot_prompt)
print(one_result)


print("\n" + "=" * 70)
print("FEW-SHOT OUTPUT")
print("=" * 70)

few_result = generate_text(few_shot_prompt)
print(few_result)


# =========================================================
# COMPARISON
# =========================================================

print("\n" + "=" * 70)
print("COMPARISON")
print("=" * 70)

print("""
Evaluation Criteria:

1. RELEVANCE
   Does the post promote the AI Workshop?

2. CREATIVITY
   Is the post attractive and engaging?

3. COMPLETENESS
   Does it contain benefits and a call to action?

4. FORMAT
   Does it contain a heading and hashtags?

5. CONSISTENCY
   Does it follow the requirements of the prompt?

Few-shot prompting generally provides better control
because examples demonstrate the expected format.
""")