# -*- coding: utf-8 -*-
"""exp-11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJRpJp3k4fA3AV-zF2njx2mCXDgKsK4I
"""

!pip install -q -U google-genai

import getpass
from google import genai

# =========================================================
# EXPERIMENT 11
# COMPARATIVE ANALYSIS OF ZERO-SHOT, ONE-SHOT AND
# FEW-SHOT PROMPTING
# =========================================================

print("=" * 70)
print("COMPARATIVE ANALYSIS OF PROMPTING TECHNIQUES")
print("=" * 70)

# ---------------------------------------------------------
# API KEY
# ---------------------------------------------------------

api_key = getpass.getpass("Enter your Gemini API key: ")

client = genai.Client(api_key=api_key)

print("\nGemini API connected successfully!")


# ---------------------------------------------------------
# SAME TASK FOR ALL THREE PROMPTS
# ---------------------------------------------------------

task = """
Explain three important benefits of cloud computing
for engineering students.
"""


# ---------------------------------------------------------
# ZERO-SHOT PROMPT
# ---------------------------------------------------------

zero_shot_prompt = f"""
{task}

Give a clear and concise answer.
"""


# ---------------------------------------------------------
# ONE-SHOT PROMPT
# ---------------------------------------------------------

one_shot_prompt = f"""
Example:

Question:
Explain three benefits of Python programming for engineering students.

Answer:
1. Python is easy to learn and understand.
2. It provides many libraries for engineering applications.
3. It can be used for automation, data analysis and simulation.

Now answer the following question in a similar format:

{task}
"""


# ---------------------------------------------------------
# FEW-SHOT PROMPT
# ---------------------------------------------------------

few_shot_prompt = f"""
Example 1:

Question:
Explain three benefits of Python programming for engineering students.

Answer:
1. Python is easy to learn.
2. Python has many useful libraries.
3. Python supports automation and data analysis.


Example 2:

Question:
Explain three benefits of simulation software for engineering students.

Answer:
1. It helps students understand complex engineering concepts.
2. It allows experiments without expensive physical equipment.
3. It helps analyze and visualize engineering systems.


Now answer:

{task}

Requirements:
- Give exactly three benefits.
- Explain each benefit briefly.
- Use simple engineering language.
- Number the points clearly.
"""


# ---------------------------------------------------------
# FUNCTION TO GENERATE RESPONSE
# ---------------------------------------------------------

def generate_response(prompt):

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    return response.text.strip()


# ---------------------------------------------------------
# GENERATE THREE RESPONSES
# ---------------------------------------------------------

try:

    zero_result = generate_response(zero_shot_prompt)

    one_result = generate_response(one_shot_prompt)

    few_result = generate_response(few_shot_prompt)


    # -----------------------------------------------------
    # DISPLAY OUTPUTS
    # -----------------------------------------------------

    print("\n" + "=" * 70)
    print("ZERO-SHOT RESPONSE")
    print("=" * 70)
    print(zero_result)


    print("\n" + "=" * 70)
    print("ONE-SHOT RESPONSE")
    print("=" * 70)
    print(one_result)


    print("\n" + "=" * 70)
    print("FEW-SHOT RESPONSE")
    print("=" * 70)
    print(few_result)


    # -----------------------------------------------------
    # COMPARISON TABLE
    # -----------------------------------------------------

    print("\n" + "=" * 70)
    print("COMPARATIVE ANALYSIS")
    print("=" * 70)

    print("""
Evaluation Criteria:

1. QUALITY
   Zero-shot : Basic response
   One-shot  : Improved structure
   Few-shot  : Better controlled response

2. RELEVANCE
   Check whether the response directly answers the question.

3. ACCURACY
   Check whether the information provided is correct.

4. CONSISTENCY
   Check whether the response follows the requested
   format and contains exactly three benefits.

5. OVERALL OBSERVATION
   Zero-shot prompting gives instructions without examples.
   One-shot prompting provides one example to guide the model.
   Few-shot prompting provides multiple examples and gives
   stronger control over the expected response format.
    """)

except Exception as e:

    print("\nError occurred:")
    print(e)