# -*- coding: utf-8 -*-
"""exp-12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJRpJp3k4fA3AV-zF2njx2mCXDgKsK4I
"""

!pip install -q -U google-genai

import getpass
from google import genai

# =========================================================
# EXPERIMENT 12
# PROMPT EVALUATION, COMPARISON AND REFINEMENT
# =========================================================

print("=" * 70)
print("PROMPT EVALUATION, COMPARISON AND REFINEMENT")
print("=" * 70)

# ---------------------------------------------------------
# API KEY
# ---------------------------------------------------------

api_key = getpass.getpass("Enter your Gemini API key: ")

client = genai.Client(api_key=api_key)

print("\nGemini API connected successfully!")


# ---------------------------------------------------------
# TASK
# ---------------------------------------------------------

task = """
Explain the applications of artificial intelligence in healthcare.
Give five applications suitable for engineering students.
"""


# ---------------------------------------------------------
# PROMPT 1 — BASIC
# ---------------------------------------------------------

prompt1 = f"""
{task}
"""


# ---------------------------------------------------------
# PROMPT 2 — CLEAR INSTRUCTIONS
# ---------------------------------------------------------

prompt2 = f"""
Explain the following topic:

{task}

Use simple language.
Give exactly five numbered points.
Briefly explain each application.
"""


# ---------------------------------------------------------
# PROMPT 3 — DETAILED STRUCTURED PROMPT
# ---------------------------------------------------------

prompt3 = f"""
ROLE:
You are an engineering education assistant.

TASK:
{task}

REQUIREMENTS:
1. Give exactly five applications.
2. Number the applications from 1 to 5.
3. Give a short explanation for each.
4. Use technically accurate information.
5. Use simple language suitable for engineering students.
6. Avoid unnecessary information.
7. Follow the requested format exactly.
"""


# ---------------------------------------------------------
# GENERATE RESPONSE
# ---------------------------------------------------------

def generate_response(prompt):

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    return response.text.strip()


try:

    result1 = generate_response(prompt1)
    result2 = generate_response(prompt2)
    result3 = generate_response(prompt3)


    # -----------------------------------------------------
    # DISPLAY RESPONSES
    # -----------------------------------------------------

    print("\n" + "=" * 70)
    print("RESPONSE FOR PROMPT 1")
    print("=" * 70)
    print(result1)


    print("\n" + "=" * 70)
    print("RESPONSE FOR PROMPT 2")
    print("=" * 70)
    print(result2)


    print("\n" + "=" * 70)
    print("RESPONSE FOR PROMPT 3")
    print("=" * 70)
    print(result3)


    # -----------------------------------------------------
    # EVALUATION
    # -----------------------------------------------------

    evaluation_prompt = f"""
You are evaluating three LLM responses.

TASK:
{task}

Evaluate the following responses using these criteria:

1. Relevance
2. Accuracy
3. Completeness
4. Clarity
5. Format adherence

Give each response a score from 1 to 5 for every criterion.

Then calculate the total score out of 25.

Finally:
- Identify the best-performing prompt.
- Explain why it performed best.
- Suggest an improved version of the best prompt.

RESPONSE 1:
{result1}

RESPONSE 2:
{result2}

RESPONSE 3:
{result3}
"""

    evaluation = generate_response(evaluation_prompt)


    # -----------------------------------------------------
    # DISPLAY EVALUATION
    # -----------------------------------------------------

    print("\n" + "=" * 70)
    print("PROMPT EVALUATION")
    print("=" * 70)

    print(evaluation)


    # -----------------------------------------------------
    # REFINED PROMPT
    # -----------------------------------------------------

    refinement_prompt = f"""
Create a refined prompt for the following task:

{task}

The prompt should improve:
- Relevance
- Accuracy
- Completeness
- Clarity
- Format adherence

Use clear role, task and output requirements.

Return only the refined prompt.
"""

    refined_prompt = generate_response(refinement_prompt)


    print("\n" + "=" * 70)
    print("REFINED PROMPT")
    print("=" * 70)

    print(refined_prompt)


except Exception as e:

    print("\nError occurred:")
    print(e)