# -*- coding: utf-8 -*-
"""exp10unit(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dI4RUAmeIOS0M4kQ8d_60gIqoiU0vQa
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load the tokenizer and model directly for text-to-text generation
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-small")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-small")

topic = input("Enter your research topic: ")

prompt = f"""
Research Topic: {topic}

Give:
1. Relevant keywords
2. A concise research summary
3. Possible applications
"""

# Prepare input for the model
inputs = tokenizer(prompt, return_tensors="pt")

# Generate text
outputs = model.generate(**inputs, max_new_tokens=200)

# Decode the generated text
generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

print("\nResearch Assistance Result:")
print(generated_text)