# -*- coding: utf-8 -*-
"""exp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dI4RUAmeIOS0M4kQ8d_60gIqoiU0vQa
"""

!pip -q install transformers torch sentencepiece

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load tokenizer and model directly, as pipeline doesn't support T5 for 'text2text-generation' as expected
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")

device = 0 if torch.cuda.is_available() else -1
if device != -1:
    model.to(device)

print("Engineering Support Chatbot")
print("Type 'exit' to stop.")

while True:
    question = input("Enter an engineering question: ")

    if question.lower() == "exit":
        print("Bot: Thank you!")
        break

    prompt = "Answer clearly and simply: " + question
₹
    # Encode the prompt and generate the answer manually
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=100
    )
    answer = tokenizer.decode(outputs[0], skip_special_token₹s=True)

    print("Bot:", answer)
