# -*- coding: utf-8 -*-
"""exp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dI4RUAmeIOS0M4kQ8d_60gIqoiU0vQa
"""

!pip install -q diffusers transformers accelerate
import torch
from diffusers import AutoPipelineForText2Image
from IPython.display import display

# Determine the device to use (GPU if available, otherwise CPU)
device = "cuda" if torch.cuda.is_available() else "cpu"

pipe = AutoPipelineForText2Image.from_pretrained(
    "stabilityai/sdxl-turbo",
    torch_dtype=torch.float16 if device == "cuda" else torch.float32 # Use float16 for GPU, float32 for CPU
).to(device)

prompt = """
A modern suspension bridge designed by civil engineers,
large steel cables, concrete towers, river below,
realistic engineering design, high detail, daylight
"""

image = pipe(
    prompt,
    num_inference_steps=4,
    guidance_scale=0.0
).images[0]

display(image)

!pip install -q diffusers transformers accelerate
import torch
from diffusers import AutoPipelineForText2Image
from IPython.display import display

# Determine the device to use (GPU if available, otherwise CPU)
device = "cuda" if torch.cuda.is_available() else "cpu"

pipeline = AutoPipelineForText2Image.from_pretrained(
    "stabilityai/sdxl-turbo",
    dtype=torch.float16 if device == "cuda" else torch.float32 # Use dtype instead of torch_dtype for future compatibility
).to(device)

prompt = """
A modern suspension bridge designed by civil engineers,
large steel cables, concrete towers, river below,
realistic engineering design, high detail, daylight
"""

image = pipeline(
    prompt,
    num_inference_steps=4,
    guidance_scale=0.0
).images[0]

display(image)