# -*- coding: utf-8 -*-
"""exp4 unit(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dI4RUAmeIOS0M4kQ8d_60gIqoiU0vQa
"""

!pip -q install diffusers transformers accelerate

import torch
from diffusers import StableDiffusionPipeline
from IPython.display import display

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float32
)

pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")

prompts = [
    "A robotic arm in an engineering laboratory",
    "A futuristic robotic arm in an engineering laboratory",
    "A small industrial robotic arm in a factory"
]

for prompt in prompts:
    print("\nPrompt:", prompt)
    image = pipe(prompt, num_inference_steps=20).images[0]
    display(image)