# -*- coding: utf-8 -*-
"""exp6unit(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dI4RUAmeIOS0M4kQ8d_60gIqoiU0vQa
"""

!pip -q install gTTS

from gtts import gTTS
from IPython.display import Audio, display

text = input("Enter engineering text: ")

speech = gTTS(text=text, lang="en")
speech.save("engineering_speech.mp3")

print("Speech generated successfully.")

display(Audio("engineering_speech.mp3"))