# -*- coding: utf-8 -*-
"""exp7unit(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dI4RUAmeIOS0M4kQ8d_60gIqoiU0vQa
"""

!pip -q install transformers torch

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load the tokenizer and model directly for summarization
tokenizer = AutoTokenizer.from_pretrained("sshleifer/distilbart-cnn-12-6")
model = AutoModelForSeq2SeqLM.from_pretrained("sshleifer/distilbart-cnn-12-6")

text = input("Enter engineering document text:\n")

# Prepare input for the model
inputs = tokenizer([text], max_length=1024, return_tensors='pt', truncation=True)

# Generate summary
summary_ids = model.generate(
    inputs['input_ids'],
    num_beams=4,
    max_length=100,
    min_length=30,
    early_stopping=True,
    no_repeat_ngram_size=3 # Added for better summary quality
)

# Decode the generated summary
summary_text = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print("\nSummary:")
print(summary_text)