# -*- coding: utf-8 -*-
"""exp8unit(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dI4RUAmeIOS0M4kQ8d_60gIqoiU0vQa
"""

!pip -q install transformers sentencepiece

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load the tokenizer and model directly for translation
tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-hi")
model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-en-hi")

text = input("Enter English engineering text: ")

# Prepare input for the model
inputs = tokenizer(text, return_tensors="pt")

# Generate translation
outputs = model.generate(**inputs)

# Decode the generated translation
translation_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

print("\nHindi Translation:")
print(translation_text)