# -*- coding: utf-8 -*-
"""exp9unit(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dI4RUAmeIOS0M4kQ8d_60gIqoiU0vQa
"""

!pip -q install scikit-learn

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

job = input("Enter engineering job description:\n")

n = int(input("\nEnter number of resumes: "))

resumes = []

for i in range(n):
    resume = input(f"\nEnter Resume {i+1}: ")
    resumes.append(resume)

documents = [job] + resumes

vectorizer = TfidfVectorizer(stop_words="english")
vectors = vectorizer.fit_transform(documents)

scores = cosine_similarity(vectors[0:1], vectors[1:]).flatten()

ranking = sorted(
    enumerate(scores),
    key=lambda x: x[1],
    reverse=True
)

print("\nResume Ranking:")
for rank, (index, score) in enumerate(ranking, 1):
    print(
        f"Rank {rank}: Resume {index+1} "
        f"- Match Score: {score*100:.2f}%"
    )