# -*- coding: utf-8 -*-
"""exp 37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

from sentence_transformers import SentenceTransformer
from transformers import pipeline
import faiss
import numpy as np

# -----------------------------
# 1. Documents
# -----------------------------

documents = [
    "Machine learning is a method where computers learn patterns from data.",
    "Deep learning is a type of machine learning that uses neural networks.",
    "Natural language processing enables computers to understand human language.",
    "Computer vision enables computers to analyze and understand images."
]

# -----------------------------
# 2. Embedding model
# -----------------------------

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

doc_embeddings = embedding_model.encode(documents)
doc_embeddings = np.array(doc_embeddings).astype("float32")

# -----------------------------
# 3. FAISS Vector Database
# -----------------------------

dimension = doc_embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(doc_embeddings)

# -----------------------------
# 4. User Question
# -----------------------------

question = "What is deep learning?"

question_embedding = embedding_model.encode(
    [question]
).astype("float32")

# Retrieve the most relevant document
distance, result = index.search(
    question_embedding,
    1
)

context = documents[result[0][0]]

print("Retrieved Context:")
print(context)

# -----------------------------
# 5. Answer Generation
# -----------------------------

generator = pipeline(
    "text-generation",
    model="google/flan-t5-small"
)

prompt = f"""
Answer the question using the context below.

Context:
{context}

Question:
{question}

Answer:
"""

answer = generator(
    prompt,
    max_new_tokens=50,
    do_sample=False
)

print("\nQuestion:")
print(question)

print("\nGenerated Answer:")
print(answer[0]["generated_text"])
