# -*- coding: utf-8 -*-
"""exp 38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

from sentence_transformers import SentenceTransformer
from transformers import pipeline
import faiss
import numpy as np

# --------------------------------
# 1. Document Loading
# --------------------------------

document = """
Artificial intelligence is a field of computer science.
Machine learning allows computers to learn from data.
Deep learning uses neural networks with multiple layers.
Natural language processing helps computers understand human language.
Computer vision allows computers to understand images and videos.
"""

print("Original Document:")
print(document)

# --------------------------------
# 2. Text Chunking
# --------------------------------

chunks = [
    sentence.strip()
    for sentence in document.split(".")
    if sentence.strip()
]

print("\nDocument Chunks:")

for i, chunk in enumerate(chunks, 1):
    print(i, ":", chunk)

# --------------------------------
# 3. Generate Embeddings
# --------------------------------

embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

embeddings = embedding_model.encode(chunks)

embeddings = np.array(
    embeddings
).astype("float32")

# --------------------------------
# 4. Create FAISS Vector Database
# --------------------------------

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embeddings)

print("\nNumber of vectors stored:",
      index.ntotal)

# --------------------------------
# 5. User Query
# --------------------------------

question = "What does deep learning use?"

query_embedding = embedding_model.encode(
    [question]
).astype("float32")

# --------------------------------
# 6. Retrieve Relevant Documents
# --------------------------------

k = 2

distances, indices = index.search(
    query_embedding,
    k
)

retrieved_chunks = []

for i in indices[0]:
    retrieved_chunks.append(chunks[i])

context = "\n".join(retrieved_chunks)

print("\nRetrieved Context:")
print(context)

# --------------------------------
# 7. Answer Generation
# --------------------------------

generator = pipeline(
    "text-generation",
    model="distilgpt2"
)

prompt = f"""
Context:
{context}

Question:
{question}

Answer:
"""

result = generator(
    prompt,
    max_new_tokens=50,
    do_sample=False
)

# --------------------------------
# 8. Display Final Answer
# --------------------------------

generated_text = result[0]["generated_text"]

answer = generated_text.split("Answer:")[-1].strip()

print("\nQuestion:")
print(question)

print("\nFinal Answer:")
print(answer)
