# -*- coding: utf-8 -*-
"""exp 39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# --------------------------------
# 1. Create domain-specific documents
# --------------------------------

documents = [
    Document(
        page_content="Python is a high-level programming language used for software development."
    ),
    Document(
        page_content="Machine learning enables computers to learn patterns from data."
    ),
    Document(
        page_content="Deep learning uses neural networks with multiple layers."
    ),
    Document(
        page_content="Computer vision allows computers to understand images and videos."
    ),
    Document(
        page_content="Natural language processing helps computers understand human language."
    )
]

# --------------------------------
# 2. Create embeddings
# --------------------------------

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# --------------------------------
# 3. Create vector database
# --------------------------------

vector_db = FAISS.from_documents(
    documents,
    embeddings
)

print("Domain-specific chatbot is ready!")

# --------------------------------
# 4. Chatbot
# --------------------------------

while True:

    question = input("\nYou: ")

    if question.lower() == "exit":
        print("Chatbot: Goodbye!")
        break

    # Retrieve relevant documents
    results = vector_db.similarity_search(
        question,
        k=2
    )

    print("\nChatbot:")

    for result in results:
        print("-", result.page_content)
