# -*- coding: utf-8 -*-
"""exp 35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

documents = [
    "Python is a popular programming language.",
    "Machine learning learns patterns from data.",
    "Deep learning uses neural networks.",
    "Natural language processing deals with human language.",
    "Computer vision helps computers understand images."
]

# Generate embeddings
embeddings = model.encode(documents)

# Convert to NumPy
embeddings = np.array(embeddings).astype("float32")

# Create FAISS index
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)

# Add documents
index.add(embeddings)

# Query
query = "How do computers understand pictures?"
query_embedding = model.encode([query]).astype("float32")

# Search
k = 3
distances, indices = index.search(query_embedding, k)

print("Query:", query)
print("\nTop 3 Results:")

for i, distance in zip(indices[0], distances[0]):
    print(f"Distance: {distance:.4f}")
    print(documents[i])
    print()
