# -*- coding: utf-8 -*-
"""exp 40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# --------------------------------
# 1. Knowledge Base
# --------------------------------

documents = [
    Document(
        page_content="Machine learning is a subset of artificial intelligence."
    ),
    Document(
        page_content="Supervised learning uses labelled training data."
    ),
    Document(
        page_content="Unsupervised learning uses unlabelled data."
    ),
    Document(
        page_content="Reinforcement learning learns using rewards and penalties."
    ),
    Document(
        page_content="Deep learning uses neural networks with multiple layers."
    )
]

# --------------------------------
# 2. Create embeddings
# --------------------------------

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# --------------------------------
# 3. Create vector database
# --------------------------------

vector_db = FAISS.from_documents(
    documents,
    embeddings
)

# --------------------------------
# 4. Conversation history
# --------------------------------

conversation_history = []

print("Context-Aware Chatbot")
print("Type 'exit' to stop.")

# --------------------------------
# 5. Chatbot
# --------------------------------

while True:

    question = input("\nYou: ")

    if question.lower() == "exit":
        print("Bot: Goodbye!")
        break

    # Retrieve relevant documents
    results = vector_db.similarity_search(
        question,
        k=2
    )

    context = "\n".join(
        result.page_content
        for result in results
    )

    # Store conversation
    conversation_history.append(question)

    print("\nBot:")
    print(context)

    # Display previous questions
    if len(conversation_history) > 1:

        print("\nPrevious Questions:")

        for q in conversation_history[:-1]:
            print("-", q)
