# -*- coding: utf-8 -*-
"""exp 33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

from sentence_transformers import SentenceTransformer, util

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

documents = [
    "Python is a programming language.",
    "Machine learning allows computers to learn from data.",
    "Deep learning uses neural networks.",
    "The weather is sunny today."
]

query = "How do computers learn from data?"

# Generate embeddings
doc_embeddings = model.encode(documents, convert_to_tensor=True)
query_embedding = model.encode(query, convert_to_tensor=True)

# Calculate similarity
similarities = util.cos_sim(query_embedding, doc_embeddings)[0]

print("Query:", query)
print("\nSimilarity Results:")

for doc, score in zip(documents, similarities):
    print(f"{score:.4f} -> {doc}")

# Most similar document
best_index = similarities.argmax()

print("\nMost Similar Document:")
print(documents[best_index])
