# -*- coding: utf-8 -*-
"""exp 42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# --------------------------------
# 1. Multiple Documents
# --------------------------------

documents = {
    "python.txt": [
        "Python is a high-level programming language.",
        "Python is widely used for data science.",
        "Python supports object-oriented programming."
    ],

    "machine_learning.txt": [
        "Machine learning learns patterns from data.",
        "Supervised learning uses labelled data.",
        "Unsupervised learning uses unlabelled data."
    ],

    "computer_vision.txt": [
        "Computer vision deals with image understanding.",
        "Image classification assigns labels to images.",
        "Object detection identifies objects in images."
    ]
}

# --------------------------------
# 2. Combine all documents
# --------------------------------

texts = []
file_names = []

for file_name, content in documents.items():

    for sentence in content:

        texts.append(sentence)
        file_names.append(file_name)

# --------------------------------
# 3. Generate embeddings
# --------------------------------

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

embeddings = model.encode(
    texts
)

embeddings = np.array(
    embeddings
).astype("float32")

# --------------------------------
# 4. Create FAISS database
# --------------------------------

index = faiss.IndexFlatL2(
    embeddings.shape[1]
)

index.add(embeddings)

print("Multiple Document Assistant Ready!")

# --------------------------------
# 5. Question Answering
# --------------------------------

while True:

    question = input("\nQuestion: ")

    if question.lower() == "exit":
        print("Assistant: Goodbye!")
        break

    # Create query embedding
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    # Retrieve top 3 results
    distances, indices = index.search(
        query_embedding,
        3
    )

    print("\nRelevant Documents:")

    for i in indices[0]:

        print("\nFile:", file_names[i])
        print("Information:", texts[i])
