# -*- coding: utf-8 -*-
"""exp 41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# --------------------------------
# 1. External document
# --------------------------------

documents = [
    "The college library is open from 8 AM to 8 PM.",
    "Students can borrow up to five books.",
    "Books can be issued for fourteen days.",
    "The library provides computers and internet access.",
    "Students must carry their identity card."
]

# --------------------------------
# 2. Generate embeddings
# --------------------------------

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

embeddings = model.encode(
    documents
)

embeddings = np.array(
    embeddings
).astype("float32")

# --------------------------------
# 3. Create FAISS database
# --------------------------------

index = faiss.IndexFlatL2(
    embeddings.shape[1]
)

index.add(embeddings)

print("Document Assistant Ready!")

# --------------------------------
# 4. Question Answering
# --------------------------------

while True:

    question = input("\nAsk a question: ")

    if question.lower() == "exit":
        print("Assistant: Goodbye!")
        break

    # Convert question into embedding
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    # Retrieve relevant document
    distances, indices = index.search(
        query_embedding,
        1
    )

    answer = documents[indices[0][0]]

    print("\nAssistant:")
    print(answer)
