# -*- coding: utf-8 -*-
"""exp 34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer("all-MiniLM-L6-v2")

documents = [
    "Artificial intelligence is used in many applications.",
    "Python is widely used for data science.",
    "Machine learning is a branch of artificial intelligence.",
    "Football is a popular sport."
]

query = "What is a branch of artificial intelligence?"

# Generate embeddings
doc_embeddings = model.encode(documents)
query_embedding = model.encode([query])

# Cosine similarity
scores = cosine_similarity(query_embedding, doc_embeddings)[0]

# Display results
results = sorted(
    zip(documents, scores),
    key=lambda x: x[1],
    reverse=True
)

print("Query:", query)
print("\nSemantic Search Results:")

for document, score in results:
    print(f"Score: {score:.4f}")
    print(document)
    print()
