# -*- coding: utf-8 -*-
"""exp 36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrFF6db9zpYRfwS6zs9cy9rIDDDQJ9uu
"""

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

documents = [
    "Python is useful for programming.",
    "Machine learning uses training data.",
    "Deep learning uses artificial neural networks.",
    "SQL is used for database management.",
    "Computer vision processes images.",
    "NLP processes human language."
]

# Create embeddings
embeddings = model.encode(documents)
embeddings = np.array(embeddings).astype("float32")

# Create vector database
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

# User query
query = "What technology processes human language?"

query_embedding = model.encode([query]).astype("float32")

# Top-K retrieval
k = 3
distances, indices = index.search(query_embedding, k)

print("Query:", query)
print("\nTop-K Retrieved Documents:")

for rank, (i, distance) in enumerate(
    zip(indices[0], distances[0]), start=1
):
    print(f"\nRank {rank}")
    print("Document:", documents[i])
    print("Distance:", round(float(distance), 4))
